---
  - name: elk playbook
    hosts: elk
    become: true
    tasks:

    - name: set vm.max map count to 262144 in sysctl
      sysctl: name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }

    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      pip:
        name: docker

    - name: Install docker container sebp/elk:761
      community.docker.docker_container:
        name: Elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"

    - name: Systemd used to restart
      ansible.builtin.systemd:
        name: docker
        enabled: yes
