---
  - name: Install and configure metricbeat
    hosts: webservers
    become: true
    tasks:

      - name: Download Metricbeat
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.>
      - name: Install Metricbeat
        command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

      - name: Drop Metricbeat config file
        copy:
          src: /etc/ansible/files/metricbeat-config.yml
          dest: /etc/metricbeat/metricbeat.yml

      - name: Enable and configure docker module for Metricbeat
        command: metricbeat modules enable docker

      - name: Setup Metricbeat
        command: metricbeat setup

      - name: Start Metricbeat
        command: service metricbeat start

      - name: Enable service Metricbeat on boot
        ansible.builtin.systemd:
          name: metricbeat
          enabled: yes

